version: '3'

services:
  web:
    build: ./django
    command: python manage.py runserver 0.0.0.0:8000
    volumes: 
      - .:/code
    ports: 
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword

  nginx:  
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx:/usr/share/nginx/html
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - web
